/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/mechanical_keyboard.glb --types --output ./src/components/MechanicalKeyboard.tsx 
Author: virtualtimecapsule (https://sketchfab.com/virtualtimecapsule)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mechanical-keyboard-0161b6232216457aa8f4f3393960ec85
Title: Mechanical keyboard
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type{ GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Model_material0_0: THREE.Mesh
    Model_material0_0_1: THREE.Mesh
    Model_material0_0_2: THREE.Mesh
    Model_material0_0_3: THREE.Mesh
    Model_material0_0_4: THREE.Mesh
    Model_material0_0_5: THREE.Mesh
  }
  materials: {
    material0: THREE.MeshBasicMaterial
  }
}

export function Keyboard(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mechanical_keyboard.glb') as unknown as GLTFResult
  return (
    <group scale={[15,15,15]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_1.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_2.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_3.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_4.geometry} material={materials.material0} />
          <mesh geometry={nodes.Model_material0_0_5.geometry} material={materials.material0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/mechanical_keyboard.glb')
